/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as AdvertiserRouteImport } from './routes/advertiser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRatingsIndexRouteImport } from './routes/api/ratings/index'
import { Route as ApiAdsIndexRouteImport } from './routes/api/ads/index'
import { Route as ApiUploadsAvatarRouteImport } from './routes/api/uploads/avatar'
import { Route as ApiFleetPenaltiesRouteImport } from './routes/api/fleet/penalties'
import { Route as ApiFleetLiveRouteImport } from './routes/api/fleet/live'
import { Route as ApiFleetIntervalsRouteImport } from './routes/api/fleet/intervals'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuditorAssignRouteImport } from './routes/api/auditor/assign'
import { Route as ApiAdsMineRouteImport } from './routes/api/ads/mine'
import { Route as ApiAdsIdIndexRouteImport } from './routes/api/ads/$id/index'
import { Route as ApiUploadsAvatarIdRouteImport } from './routes/api/uploads/avatar/$id'
import { Route as ApiRatingsSummaryBusIdRouteImport } from './routes/api/ratings/summary/$busId'
import { Route as ApiFleetLocationBusIdRouteImport } from './routes/api/fleet/location/$busId'
import { Route as ApiAdsIdViewRouteImport } from './routes/api/ads/$id/view'
import { Route as ApiAdsIdLikeRouteImport } from './routes/api/ads/$id/like'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserRoute = AdvertiserRouteImport.update({
  id: '/advertiser',
  path: '/advertiser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsIndexRoute = ApiRatingsIndexRouteImport.update({
  id: '/api/ratings/',
  path: '/api/ratings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIndexRoute = ApiAdsIndexRouteImport.update({
  id: '/api/ads/',
  path: '/api/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsAvatarRoute = ApiUploadsAvatarRouteImport.update({
  id: '/api/uploads/avatar',
  path: '/api/uploads/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetPenaltiesRoute = ApiFleetPenaltiesRouteImport.update({
  id: '/api/fleet/penalties',
  path: '/api/fleet/penalties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetLiveRoute = ApiFleetLiveRouteImport.update({
  id: '/api/fleet/live',
  path: '/api/fleet/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetIntervalsRoute = ApiFleetIntervalsRouteImport.update({
  id: '/api/fleet/intervals',
  path: '/api/fleet/intervals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditorAssignRoute = ApiAuditorAssignRouteImport.update({
  id: '/api/auditor/assign',
  path: '/api/auditor/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsMineRoute = ApiAdsMineRouteImport.update({
  id: '/api/ads/mine',
  path: '/api/ads/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIdIndexRoute = ApiAdsIdIndexRouteImport.update({
  id: '/api/ads/$id/',
  path: '/api/ads/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsAvatarIdRoute = ApiUploadsAvatarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUploadsAvatarRoute,
} as any)
const ApiRatingsSummaryBusIdRoute = ApiRatingsSummaryBusIdRouteImport.update({
  id: '/api/ratings/summary/$busId',
  path: '/api/ratings/summary/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFleetLocationBusIdRoute = ApiFleetLocationBusIdRouteImport.update({
  id: '/api/fleet/location/$busId',
  path: '/api/fleet/location/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIdViewRoute = ApiAdsIdViewRouteImport.update({
  id: '/api/ads/$id/view',
  path: '/api/ads/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdsIdLikeRoute = ApiAdsIdLikeRouteImport.update({
  id: '/api/ads/$id/like',
  path: '/api/ads/$id/like',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/ads/mine': typeof ApiAdsMineRoute
  '/api/auditor/assign': typeof ApiAuditorAssignRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/fleet/intervals': typeof ApiFleetIntervalsRoute
  '/api/fleet/live': typeof ApiFleetLiveRoute
  '/api/fleet/penalties': typeof ApiFleetPenaltiesRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRouteWithChildren
  '/api/ads/': typeof ApiAdsIndexRoute
  '/api/ratings/': typeof ApiRatingsIndexRoute
  '/api/ads/$id/like': typeof ApiAdsIdLikeRoute
  '/api/ads/$id/view': typeof ApiAdsIdViewRoute
  '/api/fleet/location/$busId': typeof ApiFleetLocationBusIdRoute
  '/api/ratings/summary/$busId': typeof ApiRatingsSummaryBusIdRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
  '/api/ads/$id/': typeof ApiAdsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/ads/mine': typeof ApiAdsMineRoute
  '/api/auditor/assign': typeof ApiAuditorAssignRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/fleet/intervals': typeof ApiFleetIntervalsRoute
  '/api/fleet/live': typeof ApiFleetLiveRoute
  '/api/fleet/penalties': typeof ApiFleetPenaltiesRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRouteWithChildren
  '/api/ads': typeof ApiAdsIndexRoute
  '/api/ratings': typeof ApiRatingsIndexRoute
  '/api/ads/$id/like': typeof ApiAdsIdLikeRoute
  '/api/ads/$id/view': typeof ApiAdsIdViewRoute
  '/api/fleet/location/$busId': typeof ApiFleetLocationBusIdRoute
  '/api/ratings/summary/$busId': typeof ApiRatingsSummaryBusIdRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
  '/api/ads/$id': typeof ApiAdsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/ads/mine': typeof ApiAdsMineRoute
  '/api/auditor/assign': typeof ApiAuditorAssignRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/fleet/intervals': typeof ApiFleetIntervalsRoute
  '/api/fleet/live': typeof ApiFleetLiveRoute
  '/api/fleet/penalties': typeof ApiFleetPenaltiesRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRouteWithChildren
  '/api/ads/': typeof ApiAdsIndexRoute
  '/api/ratings/': typeof ApiRatingsIndexRoute
  '/api/ads/$id/like': typeof ApiAdsIdLikeRoute
  '/api/ads/$id/view': typeof ApiAdsIdViewRoute
  '/api/fleet/location/$busId': typeof ApiFleetLocationBusIdRoute
  '/api/ratings/summary/$busId': typeof ApiRatingsSummaryBusIdRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
  '/api/ads/$id/': typeof ApiAdsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/ads/mine'
    | '/api/auditor/assign'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/signup'
    | '/api/fleet/intervals'
    | '/api/fleet/live'
    | '/api/fleet/penalties'
    | '/api/uploads/avatar'
    | '/api/ads/'
    | '/api/ratings/'
    | '/api/ads/$id/like'
    | '/api/ads/$id/view'
    | '/api/fleet/location/$busId'
    | '/api/ratings/summary/$busId'
    | '/api/uploads/avatar/$id'
    | '/api/ads/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/ads/mine'
    | '/api/auditor/assign'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/signup'
    | '/api/fleet/intervals'
    | '/api/fleet/live'
    | '/api/fleet/penalties'
    | '/api/uploads/avatar'
    | '/api/ads'
    | '/api/ratings'
    | '/api/ads/$id/like'
    | '/api/ads/$id/view'
    | '/api/fleet/location/$busId'
    | '/api/ratings/summary/$busId'
    | '/api/uploads/avatar/$id'
    | '/api/ads/$id'
  id:
    | '__root__'
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/ads/mine'
    | '/api/auditor/assign'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/signup'
    | '/api/fleet/intervals'
    | '/api/fleet/live'
    | '/api/fleet/penalties'
    | '/api/uploads/avatar'
    | '/api/ads/'
    | '/api/ratings/'
    | '/api/ads/$id/like'
    | '/api/ads/$id/view'
    | '/api/fleet/location/$busId'
    | '/api/ratings/summary/$busId'
    | '/api/uploads/avatar/$id'
    | '/api/ads/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiserRoute: typeof AdvertiserRoute
  AuditorRoute: typeof AuditorRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  PassengerRoute: typeof PassengerRoute
  SignupRoute: typeof SignupRoute
  ApiAdsMineRoute: typeof ApiAdsMineRoute
  ApiAuditorAssignRoute: typeof ApiAuditorAssignRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiFleetIntervalsRoute: typeof ApiFleetIntervalsRoute
  ApiFleetLiveRoute: typeof ApiFleetLiveRoute
  ApiFleetPenaltiesRoute: typeof ApiFleetPenaltiesRoute
  ApiUploadsAvatarRoute: typeof ApiUploadsAvatarRouteWithChildren
  ApiAdsIndexRoute: typeof ApiAdsIndexRoute
  ApiRatingsIndexRoute: typeof ApiRatingsIndexRoute
  ApiAdsIdLikeRoute: typeof ApiAdsIdLikeRoute
  ApiAdsIdViewRoute: typeof ApiAdsIdViewRoute
  ApiFleetLocationBusIdRoute: typeof ApiFleetLocationBusIdRoute
  ApiRatingsSummaryBusIdRoute: typeof ApiRatingsSummaryBusIdRoute
  ApiAdsIdIndexRoute: typeof ApiAdsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser': {
      id: '/advertiser'
      path: '/advertiser'
      fullPath: '/advertiser'
      preLoaderRoute: typeof AdvertiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings/': {
      id: '/api/ratings/'
      path: '/api/ratings'
      fullPath: '/api/ratings/'
      preLoaderRoute: typeof ApiRatingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/': {
      id: '/api/ads/'
      path: '/api/ads'
      fullPath: '/api/ads/'
      preLoaderRoute: typeof ApiAdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar': {
      id: '/api/uploads/avatar'
      path: '/api/uploads/avatar'
      fullPath: '/api/uploads/avatar'
      preLoaderRoute: typeof ApiUploadsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/penalties': {
      id: '/api/fleet/penalties'
      path: '/api/fleet/penalties'
      fullPath: '/api/fleet/penalties'
      preLoaderRoute: typeof ApiFleetPenaltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/live': {
      id: '/api/fleet/live'
      path: '/api/fleet/live'
      fullPath: '/api/fleet/live'
      preLoaderRoute: typeof ApiFleetLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/intervals': {
      id: '/api/fleet/intervals'
      path: '/api/fleet/intervals'
      fullPath: '/api/fleet/intervals'
      preLoaderRoute: typeof ApiFleetIntervalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auditor/assign': {
      id: '/api/auditor/assign'
      path: '/api/auditor/assign'
      fullPath: '/api/auditor/assign'
      preLoaderRoute: typeof ApiAuditorAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/mine': {
      id: '/api/ads/mine'
      path: '/api/ads/mine'
      fullPath: '/api/ads/mine'
      preLoaderRoute: typeof ApiAdsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/$id/': {
      id: '/api/ads/$id/'
      path: '/api/ads/$id'
      fullPath: '/api/ads/$id/'
      preLoaderRoute: typeof ApiAdsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar/$id': {
      id: '/api/uploads/avatar/$id'
      path: '/$id'
      fullPath: '/api/uploads/avatar/$id'
      preLoaderRoute: typeof ApiUploadsAvatarIdRouteImport
      parentRoute: typeof ApiUploadsAvatarRoute
    }
    '/api/ratings/summary/$busId': {
      id: '/api/ratings/summary/$busId'
      path: '/api/ratings/summary/$busId'
      fullPath: '/api/ratings/summary/$busId'
      preLoaderRoute: typeof ApiRatingsSummaryBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fleet/location/$busId': {
      id: '/api/fleet/location/$busId'
      path: '/api/fleet/location/$busId'
      fullPath: '/api/fleet/location/$busId'
      preLoaderRoute: typeof ApiFleetLocationBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/$id/view': {
      id: '/api/ads/$id/view'
      path: '/api/ads/$id/view'
      fullPath: '/api/ads/$id/view'
      preLoaderRoute: typeof ApiAdsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ads/$id/like': {
      id: '/api/ads/$id/like'
      path: '/api/ads/$id/like'
      fullPath: '/api/ads/$id/like'
      preLoaderRoute: typeof ApiAdsIdLikeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUploadsAvatarRouteChildren {
  ApiUploadsAvatarIdRoute: typeof ApiUploadsAvatarIdRoute
}

const ApiUploadsAvatarRouteChildren: ApiUploadsAvatarRouteChildren = {
  ApiUploadsAvatarIdRoute: ApiUploadsAvatarIdRoute,
}

const ApiUploadsAvatarRouteWithChildren =
  ApiUploadsAvatarRoute._addFileChildren(ApiUploadsAvatarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiserRoute: AdvertiserRoute,
  AuditorRoute: AuditorRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  PassengerRoute: PassengerRoute,
  SignupRoute: SignupRoute,
  ApiAdsMineRoute: ApiAdsMineRoute,
  ApiAuditorAssignRoute: ApiAuditorAssignRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiFleetIntervalsRoute: ApiFleetIntervalsRoute,
  ApiFleetLiveRoute: ApiFleetLiveRoute,
  ApiFleetPenaltiesRoute: ApiFleetPenaltiesRoute,
  ApiUploadsAvatarRoute: ApiUploadsAvatarRouteWithChildren,
  ApiAdsIndexRoute: ApiAdsIndexRoute,
  ApiRatingsIndexRoute: ApiRatingsIndexRoute,
  ApiAdsIdLikeRoute: ApiAdsIdLikeRoute,
  ApiAdsIdViewRoute: ApiAdsIdViewRoute,
  ApiFleetLocationBusIdRoute: ApiFleetLocationBusIdRoute,
  ApiRatingsSummaryBusIdRoute: ApiRatingsSummaryBusIdRoute,
  ApiAdsIdIndexRoute: ApiAdsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
