/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as AdvertiserRouteImport } from './routes/advertiser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadsAvatarRouteImport } from './routes/api/uploads/avatar'
import { Route as ApiUploadsAvatarIdRouteImport } from './routes/api/uploads/avatar/$id'

const ApiUploadsAvatarRoute = ApiUploadsAvatarRouteImport.update({
  id: '/api/uploads/avatar',
  path: '/api/uploads/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsAvatarIdRoute = ApiUploadsAvatarIdRouteImport.update({
  id: '/api/uploads/avatar/$id',
  path: '/api/uploads/avatar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserRoute = AdvertiserRouteImport.update({
  id: '/advertiser',
  path: '/advertiser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertiser': typeof AdvertiserRoute
  '/auditor': typeof AuditorRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/passenger': typeof PassengerRoute
  '/signup': typeof SignupRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/avatar/$id': typeof ApiUploadsAvatarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/uploads/avatar'
    | '/api/uploads/avatar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/uploads/avatar'
    | '/api/uploads/avatar/$id'
  id:
    | '__root__'
    | '/'
    | '/advertiser'
    | '/auditor'
    | '/login'
    | '/owner'
    | '/passenger'
    | '/signup'
    | '/api/uploads/avatar'
    | '/api/uploads/avatar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiserRoute: typeof AdvertiserRoute
  AuditorRoute: typeof AuditorRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  PassengerRoute: typeof PassengerRoute
  SignupRoute: typeof SignupRoute
  ApiUploadsAvatarRoute: typeof ApiUploadsAvatarRoute
  ApiUploadsAvatarIdRoute: typeof ApiUploadsAvatarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser': {
      id: '/advertiser'
      path: '/advertiser'
      fullPath: '/advertiser'
      preLoaderRoute: typeof AdvertiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar': {
      id: '/api/uploads/avatar'
      path: '/api/uploads/avatar'
      fullPath: '/api/uploads/avatar'
      preLoaderRoute: typeof ApiUploadsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar/$id': {
      id: '/api/uploads/avatar/$id'
      path: '/api/uploads/avatar/$id'
      fullPath: '/api/uploads/avatar/$id'
      preLoaderRoute: typeof ApiUploadsAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiserRoute: AdvertiserRoute,
  AuditorRoute: AuditorRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  PassengerRoute: PassengerRoute,
  SignupRoute: SignupRoute,
  ApiUploadsAvatarRoute: ApiUploadsAvatarRoute,
  ApiUploadsAvatarIdRoute: ApiUploadsAvatarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
